"""Modificación de campo fecha en modelo Turno como tipo Date

Revision ID: c7cf7a27871d
Revises: 
Create Date: 2024-08-27 20:52:57.800714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7cf7a27871d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
